#! /bin/sh

echo "Need to copy .ssh directory over from existing machine"
echo "After copying the directory, and not before"
echo
echo "Press any key to continue"
while [ true ] ; do
read -t 3 -n 1
if [ $? = 0 ] ; then
exit ;
else
echo "waiting for the keypress"
fi
done
