#! /bin/bash

# Fail script if any command fails
set -e

## keep track of the last executed command
trap 'last_command=$current_command; current_command=$BASH_COMMAND' DEBUG
## echo an error message before exiting
trap 'echo "\"${last_command}\" command failed with exit code $?."' EXIT

# ActiveState tool
sh <(curl -q https://platform.activestate.com/dl/cli/install.sh)

# ActiveState BE Tooling
yay --noconfirm -S yarn
yay --noconfirm -S node
yay --noconfirm -S prettier
yay --noconfirm -S jq
yay --noconfirm -S python37
yay --noconfirm -S python-black
yay --noconfirm -S python-isort
